import React from 'react';
import { Volume2, VolumeX, Moon, Sun, RotateCcw, GraduationCap } from 'lucide-react';
import { audioService } from '../../utils/audio';

export const TopNavControls = (props: any) => {
  const { isDark, onToggleTheme, isAudioMuted, onToggleMute, isAmbientActive, onToggleAmbient, isExploded, onReassemble } = props;
  const theme = isDark ? 'bg-white/5 hover:bg-white/10 text-slate-200 border-white/10' : 'bg-slate-100 hover:bg-slate-200 text-slate-800 border-slate-300';
  return <header className="fixed top-0 left-0 right-0 z-40 p-4 sm:p-6 flex justify-between items-center pointer-events-none"><div className="pointer-events-auto flex items-center gap-3"><div className="flex flex-col"><span className="font-mono-tech text-xs tracking-[0.25em] font-semibold">SARANG R N</span><span className="font-mono-tech text-[10px] tracking-widest">PORTFOLIO ARCHIVE // 2026</span></div></div><div className="pointer-events-auto flex items-center gap-2 sm:gap-3">{isExploded && <button onClick={() => { audioService.playClick(); onReassemble(); }} className="flex items-center gap-1.5 px-3 py-1.5 rounded-sm font-mono-tech text-xs tracking-wider border"><RotateCcw className="w-3.5 h-3.5" /><span className="hidden sm:inline">REASSEMBLE</span></button>}<a href={'https://mcacertificate.vercel.app/'} target="_blank" rel="noopener noreferrer" onClick={() => audioService.playClick()} className={'flex items-center gap-1.5 px-3 py-1.5 rounded-sm font-mono-tech text-xs tracking-wider border transition-all duration-200 cursor-pointer ' + theme} title="View PG Degree Certificate"><GraduationCap className="w-3.5 h-3.5" /><span>VIEW PG DEGREE CERTIFICATE</span></a><button onClick={() => { audioService.playClick(); onToggleAmbient(); }} className="flex items-center gap-1.5 px-3 py-1.5 rounded-sm font-mono-tech text-xs tracking-wider border"><span>♪</span><span>{isAmbientActive ? 'SOUND ON' : 'SOUND OFF'}</span></button><button onClick={() => { audioService.playClick(); onToggleMute(); }} className="p-2 rounded-sm border"><>{isAudioMuted ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4" />}</></button><button onClick={() => { audioService.playClick(); onToggleTheme(); }} className={'flex items-center gap-1.5 px-3 py-1.5 rounded-sm font-mono-tech text-xs tracking-wider border ' + theme}>{isDark ? <><Sun className="w-3.5 h-3.5" /><span>LIGHT</span></> : <><Moon className="w-3.5 h-3.5" /><span>DARK</span></>}</button></div></header>;
};
